apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: bankapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api-service
  namespace: bankapp
spec:
  selector:
    app: bank-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
